apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8888
  selector:
    app: hello-app
  type: ClusterIP
